### PR TITLE
Rename i_df and investigation_df.

### PR DESCRIPTION
**Pull request by ptth222**
i_df and investigation_df are not a DataFrame as indicated in parameter typing or as the name would suggest. It's actually a dictionary of DataFrames and lists of DataFrames. I have renamed them to reflect this.

### CODE REVIEW

**Review by proccaserra — APPROVED** [review]
Works but breaks many tests which need upgrading.
On me.

**Comment by ptth222** [comment]
Interesting. I wouldn't have expected this one to break anything since it just renames variables/parameters. I am looking into the testing now to try and understand how it all works to try and make changes to them so some of these PRs will pass.

**Comment by terazus** [comment]
I did not look into the details of why tests failed but my gut feeling is that, since you changed a function signature (the constructor of `ISAInvestigationValidator`), any direct call to that function in a test through a named parameters would break.
for instance:
```
validator = ISAInvestigationValidator(investigation_df=my_dataframe, ....)
```

**Comment by ptth222** [comment]
That's strange. I don't see @terazus comments, but I got an email about it. I think you are right. I will look through the tests and try to find the renaming changes.

**Comment by ptth222** [comment]
I did not mean to trigger a rerun on this when I rebased it. I am working on looking at the broken tests now.

**Comment by terazus** [comment]
> I did not mean to trigger a rerun on this when I rebased it. I am working on looking at the broken tests now.

You can mark PR as draft if you are not ready yet.

**Comment by ptth222** [comment]
@terazus It is ready now. It initially ran when I did the rebase because the PR was already here and I think it was previously approved. The last commit I made triggered another rerun, but that is good to go.

**Pull request merged**
