### PR TITLE
Improve write performances with many samples

### PR DESCRIPTION
**Pull request by cpommier**
By commenting a string formating (__repr__ ) for Samples, the write time with 30 samples where divided by approximatively 10.
The output for BrAPI2ISA are consistent.
TODO: Check that this method is indeed only used for logging as it seems.

### CODE REVIEW

**Comment by cpommier** [comment]
Thanks for the answer. We tried to comment logging in models.py but without luck. 
But we haven't ben very precise. Therefore there might be an imporvment by looking at isatools.py and other files to identify all sample logging and removing them.

**Comment by Zigur** [comment]
Yes, I think that that is the way to go and either comment out or lower to DEBUG level all the Sample logging messages in `isatab.py` (and potentially elsewhere).

**Comment by cpommier** [comment]
@erikkimmel and I tried to reactivate this `__repr__` and commented as much log as seems desirable.   No luck so far, even if ` __repr__(self):  return "isatools.model.Sample` still seems to be the problematic code.

We have pushed the code to the branch so you can have a look.
Would you have the possibility to investigate this next week Erik and you, depending of both your availablities ?

**Comment by cpommier** [comment]
Hi @Zigur did you had the look at the code of this branch ? Any idea of the best way to proceed?
@proccaserra do you have any suggestion on this ?
Thanks

**Comment by cpommier** [comment]
We just found out that, with our test with 30 samples, the __repr__ method of the class sampl is called 2805 times. This seems to be a lot !

**Comment by Zigur** [comment]
Hello, @cpommier did you have any improvement with the bugfix above? We are also investigating multi-processing to improve the serialization but the excessive time taken by `__repr__()` calls would not be affected by that, I expect.

**Comment by djcomlab** [comment]
@cpommier Hi Cyril, please try out https://github.com/ISA-tools/isa-api/pull/365

**Comment by Zigur** [comment]
This is being solved with #405

**Pull request closed without merging**
