### PR TITLE
ISAv1 JSON schema for supporting (nano)materials

### PR DESCRIPTION
**Pull request by vedina**
ISAv1 JSON schema and examples for representing nanomaterials  as in [ISA-TAB-Nano](https://wiki.nci.nih.gov/display/icr/isa-tab-nano) "Material file".

Also applicable for describing substances with complex composition, not necessarily nanomaterials. The schema follows the logic of the ISA-TAB-Nano "Material file", allowing to specify the components of a material and the links between them.

### CODE REVIEW

**Comment by vedina** [comment]
@agbeltran @proccaserra @djcomlab we'll have a webinar on various topics including this material schema [Thu Nov 17](https://twitter.com/eNanoMapper/status/798185274031427584) , please consider joining.

**Comment by agbeltran** [comment]
Thank you @vedina 

We will also get back to you about the PR asap. Apologies for the silence.

**Comment by agbeltran** [comment]
@vedina would you mind sending us the connection details? I cannot find it in the calendar linked from the tweet. Thank!

**Comment by vedina** [comment]
sent by email

**Pull request merged**
