### PR TITLE
removed json2jsonLD for release

### PR DESCRIPTION
**Pull request by terazus**

### CODE REVIEW

**Comment by terazus** [comment]
The removed code is saved in this branch: https://github.com/ISA-tools/isa-api/tree/JSON-LD

**Comment by xiaofengleo** [comment]
Dear Terazus,
I am following a tutorial https://faircookbook.elixir-europe.org/content/recipes/maturity/isa-json-conversion-to-rdf-linked-data.html, in which json2jsonLD is used, like following:
from isatools.convert.json2jsonld import ISALDSerializer

I try to run that tutorial code and got error saying: ModuleNotFoundError: No module named 'isatools.convert.ISALDSerializer'
The isatools version in my environment is 0.12.0, in which I believe the json2jsonLD had been removed.

I wonder do you have any idea to use the json2jsonLD, which specific version should I use?

Best regards,
Xiaofeng

**Comment by proccaserra** [comment]
@xiaofengleo I'll owe that one. We have done major refactoring over the summer and we still need to bring the component tp production level. We'll announce it when doing an official release.

**Comment by terazus** [comment]
@xiaofengleo hello there.
While designing the JSON-LD converter we realized we couldn't make it work properly without a refactor of the model. This took quite some time but we are getting there and I'm hoping that, once we've brought the refactored model to production, we can then focus on finishing the JSON-LD converter.
Hang in there, this feature will come soon.

**Comment by jjkoehorst** [comment]
Is there an example of a JSON-LD file of what is available so far? Working on a metadata validation application which generates RDF but is currently based on JERM and schema. Would like to align this as much as possible with what the ISA API would be using.

**Comment by terazus** [comment]
@jjkoehorst There is a json-LD serializer available on master with a jupyter notebook here at section 4 and beyond: https://github.com/ISA-tools/isa-api/blob/master/isa-cookbook/content/notebooks/querying-isa-with-graphql-and-sparql.ipynb
However, we have not released the code yet and the quality of our context files (used for the LD serialisation) is still under review.

**Comment by jjkoehorst** [comment]
Thanks I checked the parent directory and also noticed https://github.com/ISA-tools/isa-api/blob/master/isa-cookbook/content/notebooks/ISA-jsonld-basic-test.ttl is this an example of a likely structure that might be implemented in the future? As I am currently using the JERM ontology, PPEO and schema among others.

```
@prefix schema: <http://schema.org/> .
@prefix void:  <http://m-unlock.nl/ontology/> .
@prefix unlock: <http://m-unlock.nl/ontology/> .
@prefix mixs:  <https://w3id.org/gensc.org/terms/> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix jerm:  <http://jermontology.org/ontology/JERMOntology#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix gbol:  <http://gbol.life/0.1/> .
@prefix dcmitype: <http://purl.org/dc/dcmitype/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix MIXS:  <https://w3id.org/gensc.org/terms/> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix empusa: <http://empusa.org/0.1/> .
@prefix xml:   <http://www.w3.org/XML/1998/namespace> .
@prefix bibo:  <http://purl.org/ontology/bibo/> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix uniprot: <http://purl.uniprot.org/core/> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix ppeo:  <http://purl.org/ppeo/PPEO.owl#> .
@prefix dc:    <http://purl.org/dc/terms/> .
@prefix wv:    <http://vocab.org/waiver/terms/norms> .
@prefix base:  <http://fairbydesign.nl/> .
```

**Comment by terazus** [comment]
The implemented ontologies are WDT, OBO and SDO. You could write your own context files (https://github.com/ISA-tools/isa-api/tree/master/isatools/resources/json-context) with JERM or PPEO to generate the proper markup.

**Comment by jjkoehorst** [comment]
I already have the application creating a complete RDF graph using a ISA-like structure its just that it was aligned with the JERM ontology but that is apparently a simplified ISA and not an official ISA mapping so I am now looking into owl:sameAs mappers and where needed additional Process elements. This is the original structure which uses a chain of hasPart allowing for very direct and simplified path queries

image

**Pull request closed without merging**
