### PR TITLE
Feat/w4m tests

### PR DESCRIPTION
**Pull request by pkrog**
Integrate all isatab2w4m tests from mtbls-dwnld project.

### CODE REVIEW

**Comment by pkrog** [comment]
Hi @djcomlab , this PR integrates all tests from the R script version. There are some failures, but I don't think its due to my changes.

**Comment by agbeltran** [comment]
Thank you @pkrog  - I will check the reason for the tests failures and get back to you.

**Comment by agbeltran** [comment]
Hi @pkrog, it seems that the error might be due to the new tests files added for w4m not being picked up, as the tests work ok locally with the new set from ISAdatasets tests branch.

**Comment by agbeltran** [comment]
Ok, the reason is that travis is bringing those datasets in the tests-dev branch on ISAdatasets. I will fix this and merge the PR.

**Comment by djcomlab** [comment]
@pkrog We are still having trouble fixing your tests - please can you have a look? They fail when running the tests with `tox` (even if running local) and our CI build runs the tests in `tox`

**Comment by djcomlab** [comment]
One of the problems was that in https://github.com/ISA-tools/ISAdatasets/blob/tests-dev/tab/MTBLS338-w4m/MTBLS338-w4m-sample-metadata.tsv some rows used `n/a` instead of `NA` so the file comparison of the output of `isatab2w4m` would always fail in `test_isatab2w4m.py:TestIsatab2w4m.test_MTBLS338`

**Pull request merged**
