### PR TITLE
Python2 support

### PR DESCRIPTION
**Pull request by althonos**
Hi, 
this PR contains fixes that make the code compatible with Python2.7.

I've tried to stick to the original source code as much as possible, but had to change one function signature:

``` python
def batch_create_assays(*args, **kwargs):
    n = kwargs['n'] if n in kwargs else 1
    ...
```

 (although usage remains the same), and slightly upgraded some string editing functions.

The current result passes the validation. I had to change the way the error messages were detected in some tests as Python2 strings **repr** method adds a **u** in front of the string to show it's a unicode string, so I used regexes to avoid that issue.

New dependencies are [enum34](https://pypi.python.org/pypi/enum34), [mock](https://pypi.python.org/pypi/mock) and [six](https://pypi.python.org/pypi/six), the two first being small backports while six helps maintaining python agnostic code (and is installed by default most of the time).

### CODE REVIEW

**Comment by djcomlab** [comment]
Hi Martin, this looks great as we hadn't originally intended to support Python 2. Will check it over.

**Comment by djcomlab** [comment]
Hi @althonos, can I just ask, is there a specific need for you to have the ISA API working in Python 2.7? Our development support only plans for 3.4+.

**Comment by althonos** [comment]
Yes, we talked about that with @proccaserra and agreed that it would be better for the various 2isa projects to use the python validator instead of the java one, but as I'm developping for 2.7 and 3.2+ I needed the validator to work with those versions as well 😄

**Comment by althonos** [comment]
And I also think the MetaboLights team is working on getting more features server-side, and they're using 2.7 as well. Although I'd prefer people to switch from 2 to 3, I think supporting 2.7 as well would get you a broader support :)

**Comment by djcomlab** [comment]
Ah OK. We'll review the pull request on our end once you've got it building successfully 😃 .

**Comment by althonos** [comment]
Working on it :)

**Comment by althonos** [comment]
Hi David, okay nevermind I'll be dropping that.
It's just that I'm currently fighting against coveralls to actually increase the coverage :)

**Comment by djcomlab** [comment]
The coverage is staying low because there are two new modules (`mw2isa` and `biocrates2isatab` in the `isatools.convert` package) introduced in the last release that were added without tests. I struggled to boost coverage yesterday and noticed it is because of these as they both have a lot of lines and are not covered at all yet.
We have to add those on our side as it depends on some data that we need to verify is correct to test the outputs.

**Comment by djcomlab** [comment]
Hi @althonos, I've merged this PR into a new branch https://github.com/ISA-tools/isa-api/tree/py2

We would like to keep it separate from the master branch for the time being but are happy to pull in changes and updates from you into the py2 branch. Please open a PR to the py2 branch if you want to keep the py2 version up-to-date.

So will close this PR since it is on the master branch.

**Comment by althonos** [comment]
Okay, I'll  try to update from times to times, if the python2 version starts failing. I think this is the good thing to do as the branch started to diverge a lot.

**Comment by lomereiter** [comment]
Hi, could you state it somewhere at the top of README that Python 2 is not officially supported? That would save users some time. Thanks!

**Comment by djcomlab** [comment]
Hi @lomereiter, there is a py2 branch that we're just assessing whether to merge into the master branch to support Python 2, but will update the documentation accordingly until that's done. Thanks for pointing it out!

**Pull request closed without merging**
